export const TOWER_TYPES = {
      gun: {
              key: "gun",
              name: "Gun",
              color: 0x55aaff,
              range: 140,
              cooldown: 360,
              damage: 11,
              cost: 25,
              mode: "single",
              damageType: "physical",
              targetsFlying: false,
              targeting: "first",
              role: "DPS constant",
              notes: "Fiable contre les vagues standards"
      },
      slow: {
              key: "slow",
              name: "Slow",
              color: 0x66ddaa,
              range: 135,
              cooldown: 520,
              damage: 4,
              cost: 38,
              mode: "slow",
              damageType: "magic",
              slowFactor: 0.45,
              slowDuration: 1200,
              targetsFlying: true,
              targeting: "first",
              role: "Contrôle",
              notes: "Ralentit les menaces rapides"
      },
      aoe: {
              key: "aoe",
              name: "AOE",
              color: 0xffaa44,
              range: 150,
              cooldown: 860,
              damage: 13,
              cost: 47,
              mode: "aoe",
              damageType: "physical",
              splashRadius: 60,
              targetsFlying: false,
              targeting: "first",
              role: "Nettoyage de packs",
              notes: "Bon contre les groupes au sol"
      },
      missile: {
              key: "missile",
              name: "Missile",
              color: 0xff8800,
              range: 180,
              cooldown: 1050,
              damage: 20,
              cost: 60,
              mode: "projectile_aoe",
              damageType: "physical",
              projectileSpeed: 280,
              splashRadius: 90,
              targetsFlying: true,
              targeting: "strong",
              role: "Polyvalente lourde",
              notes: "Zone + anti-volant"
      },
      wall: {
              key: "wall",
              name: "Wall",
              color: 0x888888,
              range: 0,
              cooldown: 0,
              damage: 0,
              cost: 12,
              mode: "wall",
              damageType: "none",
              targetsFlying: false,
              targeting: "none",
              role: "Blocage",
              notes: "Redirige les ennemis au sol"
      },
      antiArmor: {
              key: "antiArmor",
              name: "Piercer",
              color: 0xb0c4de,
              range: 160,
              cooldown: 900,
              damage: 26,
              cost: 70,
              mode: "single",
              damageType: "anti_armor",
              armorPierce: 10,
              bonusVs: ["armored", "brute", "boss"],
              bonusMultiplier: 1.45,
              targetsFlying: false,
              targeting: "strong",
              role: "Anti-élite",
              notes: "Efficace contre armored/brute/boss"
      },
      tesla: {
              key: "tesla",
              name: "Tesla",
              color: 0x8a7bff,
              range: 150,
              cooldown: 760,
              damage: 11,
              cost: 72,
              mode: "chain",
              damageType: "electric",
              chainCount: 4,
              chainRange: 95,
              chainFalloff: 0.82,
              targetsFlying: true,
              targeting: "close",
              role: "Chaîne multi-cibles",
              notes: "Saute entre ennemis proches"
      },
      pyro: {
              key: "pyro",
              name: "Pyro",
              color: 0xff5c33,
              range: 145,
              cooldown: 620,
              damage: 6,
              cost: 58,
              mode: "dot",
              damageType: "burn",
              dotDamage: 4,
              dotDuration: 2800,
              dotTick: 350,
              targetsFlying: false,
              targeting: "first",
              role: "Dégâts sur durée",
              notes: "Burn cumul léger, pression continue"
      }
}

export const TOWER_KEY_ORDER = ["gun", "slow", "aoe", "missile", "wall", "antiArmor", "tesla", "pyro"]
